version: '3.8'

services:
  audiobook_db_postgres:
    image: postgres
    container_name: android_audiobook_db_postgres
    ports:
      - 5435:5432
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Test12345*
      - POSTGRES_DB=audiobook_db